@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include FONTAWESOME/users.puml

LAYOUT_WITH_LEGEND()

Person(user, "Player", "People that play the game", $sprite="users")
Container(spa, "The Game", "T-RPG", "The main game that the customer interacts with")
Container_Ext(api, "API", "C#", "The game is made in C# and needs to run in the Terminal")
ContainerDb(db, "Database", "Textfiles", "Contains story pieces, item definitions and save games")

Rel(user, spa, "Plays")
Rel(spa, api, "Uses")
Rel(api, db, "Reads/Writes")
@enduml