@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include FONTAWESOME/users.puml

Person(user, "Player", "People that play the game", $sprite="users")
Container(spa, "The Game", "T-RPG", "The main game that the customer interacts with")

Rel(user, spa, "Plays")

@enduml